# Generated by Django 6.0.6 on 2026-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
