# Generated by Django 6.0.6 on 2026-07-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_submission_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'ordering': ['-created_at'], 'verbose_name': 'User_Feedback', 'verbose_name_plural': 'User_Feedback'},
        ),
    ]
