# Generated by Django 6.0.6 on 2026-07-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('register_id', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.IntegerField()),
                ('city', models.CharField(max_length=15)),
                ('exp', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=45)),
                ('bio', models.CharField(max_length=300)),
                ('lan', models.CharField(max_length=20)),
            ],
        ),
    ]
