# Generated by Django 6.0.6 on 2026-07-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['-created_at'], 'verbose_name': 'Professional registration', 'verbose_name_plural': 'Professional registrations'},
        ),
        migrations.AddField(
            model_name='register',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_type',
            field=models.CharField(choices=[('Lawyer', 'Lawyer'), ('Firm', 'Firm')], default='Lawyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='bio',
            field=models.TextField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='exp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='lan',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='register',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
